---
title: "Bubble Bath"
author: "Standards"
date: "2026-01-23"
categories: Standards
---

{{< video https://www.youtube.com/embed/cT7nQwQHeM4 >}}

Even though I'm a big math rock fan, I only recently discovered [standards](https://open.spotify.com/artist/2CBsUDeW88bcOdccmTodCe). All their albums are awesome and the fruit theme gives it an extra happy vibe that matches the music. But the part that makes them special is how technical the music actually is, yet it's chill and relaxed enough that you could play it in any room. That is definitely not the case for all math rock. _Bubble Bath_ sticks out for me because of its almost "cheesy" dance-like opening melody, but there's this underlying emotion and fullness in the guitar. He's not just playing it on one string--you can hear him hitting multiple strings as his fingers slide around. That lasts the whole song. But the part that really does it is the transition from the main melody to this other part (listen at [1:29](https://youtu.be/cT7nQwQHeM4?list=RDcT7nQwQHeM4&t=89)), particularly where he does a little run half way through the measure. The other cool thing is how this run part only happens every other time (listen at [0:35](https://youtu.be/cT7nQwQHeM4?list=RDcT7nQwQHeM4&t=35)).