---
title: "Reckless Love"
author: "Cory Asbury"
date: "2026-01-26"
categories: Cory Asbury
---

{{< video https://www.youtube.com/embed/6xx0d3R2LoU >}}

A while back I randomly stumbled on [this reaction video](https://www.youtube.com/watch?v=lynwOb2ZiIo) of this Cory Asbury song, for whatever reason. After watching that, then proceeding to watch the entire original video above, I got hooked on this theme of live Christian rock performances that I now listen to regularly (e.g., [Elevation Worship](https://www.youtube.com/channel/UCSf-NCzjwcnXErUBW_qeFvA), [Churchome](https://www.youtube.com/@Churchome), [Bethel Music](https://www.youtube.com/channel/UCbertc-gMbkkHuSmg0qwnxw), [TRIBL](https://www.youtube.com/@TRIBL)). The music and energy in this performance is obviously one reason why I like it, but what also makes it great is the topic of the song: [_The Parable of the Lost Sheep_](https://www.biblegateway.com/passage/?search=Luke%2015&version=NIV).

> "Now the tax collectors and sinners were all gathering around to hear Jesus. 2 But the Pharisees and the teachers of the law muttered, “This man welcomes sinners and eats with them.” 3 Then Jesus told them this parable: 4 “Suppose one of you has a hundred sheep and loses one of them. Doesn’t he leave the ninety-nine in the open country and go after the lost sheep until he finds it? 5 And when he finds it, he joyfully puts it on his shoulders 6 and goes home. Then he calls his friends and neighbors together and says, ‘Rejoice with me; I have found my lost sheep.’ 7 I tell you that in the same way there will be more rejoicing in heaven over one sinner who repents than over ninety-nine righteous persons who do not need to repent."

For some reason, this one hit home. So much so that I bought a picture representation of it to hang on my wall (and I'm not one to care much about decorating). Oh, and his Dave Matthews-esque vibe with a hoodie and Yankees hat singing about Jesus (even though Matthews doesn't wear either of those that I've seen) made me like it even more.