---
title: "My Instincts are the Enemy"
author: "American Football"
date: "2026-01-27"
categories: American Football
---

{{< video https://www.youtube.com/embed/kwRmzFAyYBw >}}

My favorite song of all time. Even though ["_Never Meant_"](https://open.spotify.com/track/6kZqCqD1r08sJAQ1TjuEpM?si=b198acae02084e0e) is considered thee all-time classic emo song (and don't get me wrong, I absolutely love it), I actually prefer [American Football's](https://en.wikipedia.org/wiki/American_Football_(band)) comeback albums from [2016](https://open.spotify.com/album/4hfxw3PXN4VZI9Cs1bRjXA?si=yqvU_SJvR1uubleQW20-PQ) and [2019](https://open.spotify.com/album/18rrpVNmpcZHJjwoUlV4FN?si=Ki6kZb5HSOivpJBoTOIcCA). It's something about the maturity of the music/lyrics that is much deeper (and relatable) at this stage of life. In the [1999 album](https://open.spotify.com/album/1oKympEq5JvFhS1asxnF8A?si=pHNlH-2KTZ61mZConrBvdg), the songs reflected their struggles as they were at the time of their college-aged selves. Now they're all 40+ year old dads still singing about life, but it dwarfs the silly issues they thought they had when they were younger. You also notice that in the original album cover they're looking at [the house](https://en.wikipedia.org/wiki/American_Football_House) from the outside looking in. In [2016](https://open.spotify.com/album/4hfxw3PXN4VZI9Cs1bRjXA?si=yqvU_SJvR1uubleQW20-PQ) it's looking from the inside looking out. This song in particular sticks out, first of all, because of the lyrical content, which to me just feels all too relatable. But also because of the bridge (see [2:28](https://youtu.be/kwRmzFAyYBw?t=148)). It doesn't seem that special at first, but the technicality of the timing of the guitar part as the bass comes in just sounds like something you don't hear too often. Like they have two different time signatures running together, which sounds contradicting and confusing, but it ends up being the perfect build up to the ending. 